package FluentEditor.editor;

/*Generated by MPS */

import jetbrains.mps.editor.runtime.cells.AbstractCellAction;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.editor.runtime.selection.SelectionUtil;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.cells.CellAction;
import jetbrains.mps.openapi.editor.cells.CellActionType;
import java.util.Objects;

public class DeleteVariant {

  /*package*/ static AbstractCellAction createAction_DELETE(final SNode node) {
    return new AbstractCellAction() {
      public String getDescriptionText() {
        return "Focus `kind` when `variant` is deleted";
      }
      public void execute(EditorContext editorContext) {
        this.execute_internal(editorContext, node);
      }
      public void execute_internal(EditorContext editorContext, SNode node) {
        if (isNotEmptyString(SPropertyOperations.getString(node, MetaAdapterFactory.getProperty(0x2d38ea1d8ed2480eL, 0xa77f95b0aabfe4dfL, 0x366702a83bbb3bafL, 0x366702a83bbb3bb0L, "kind")))) {
          SPropertyOperations.assign(node, MetaAdapterFactory.getProperty(0x2d38ea1d8ed2480eL, 0xa77f95b0aabfe4dfL, 0x366702a83bbb3bafL, 0x366702a83bbb3bb0L, "kind"), SPropertyOperations.getString(node, MetaAdapterFactory.getProperty(0x2d38ea1d8ed2480eL, 0xa77f95b0aabfe4dfL, 0x366702a83bbb3bafL, 0x366702a83bbb3bb0L, "kind")).substring(0, SPropertyOperations.getString(node, MetaAdapterFactory.getProperty(0x2d38ea1d8ed2480eL, 0xa77f95b0aabfe4dfL, 0x366702a83bbb3bafL, 0x366702a83bbb3bb0L, "kind")).length() - 1));
        }
        SelectionUtil.selectLabelCellAnSetCaret(editorContext, node, "kind", -1);
      }

    };
  }

  public static void setCellActions(EditorCell editorCell, SNode node, EditorContext context) {
    CellAction originalDelete = editorCell.getAction(CellActionType.DELETE);
    CellAction originalBackspace = editorCell.getAction(CellActionType.BACKSPACE);

    // set actions that were actually defined 
    setDefinedCellActions(editorCell, node, context);

    // If we set a DELETE action but no BACKSPACE action, 
    // use the DELETE action for BACKSPACE as well. 
    CellAction deleteAction = editorCell.getAction(CellActionType.DELETE);
    CellAction backspaceAction = editorCell.getAction(CellActionType.BACKSPACE);
    if (deleteAction != originalDelete && backspaceAction == originalBackspace) {
      editorCell.setAction(CellActionType.BACKSPACE, deleteAction);
    }
  }

  public static void setDefinedCellActions(EditorCell editorCell, SNode node, EditorContext context) {

    // set cell actions from all imported action maps 

    // set cell actions defined directly in this action map 
    editorCell.setAction(CellActionType.DELETE, createAction_DELETE(node));

  }

  public static void setDefinedCellActionsOfType(EditorCell editorCell, SNode node, EditorContext context, CellActionType actionType) {

    // set cell action(s) of the given type from imported action maps 

    // set cell action of the given type defined directly in this action map 
    if (Objects.equals(actionType, CellActionType.DELETE)) {
      editorCell.setAction(actionType, createAction_DELETE(node));
    }
  }
  private static boolean isNotEmptyString(String str) {
    return str != null && str.length() > 0;
  }
}
