package FluentEditor.actions;

/*Generated by MPS */

import org.apache.log4j.Logger;
import org.apache.log4j.LogManager;
import jetbrains.mps.openapi.actions.descriptor.NodeFactory;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.baseLanguage.logging.runtime.model.LoggingRuntime;
import org.apache.log4j.Level;

public class RichTextNodeFactory {
  private static final Logger LOG = LogManager.getLogger(RichTextNodeFactory.class);
  public static class NodeFactory_6394025033531912845 implements NodeFactory {
    public void setup(SNode newNode, SNode sampleNode, SNode enclosingNode, SModel model) {
      LoggingRuntime.logMsgView(Level.INFO, "Word node factory called", RichTextNodeFactory.class, null, null);
    }
  }
  public static class NodeFactory_6394025033531982812 implements NodeFactory {
    public void setup(SNode newNode, SNode sampleNode, SNode enclosingNode, SModel model) {
      LoggingRuntime.logMsgView(Level.INFO, "BoldWord node factory called", RichTextNodeFactory.class, null, null);
    }
  }
}
